/*
 * Nomad
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.6
 * Contact: support@hashicorp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for VariableLock
 */
public class VariableLockTest {
    private final VariableLock model = new VariableLock();

    /**
     * Model tests for VariableLock
     */
    @Test
    public void testVariableLock() {
        // TODO: test VariableLock
    }

    /**
     * Test the property 'ID'
     */
    @Test
    public void IDTest() {
        // TODO: test ID
    }

    /**
     * Test the property 'lockDelay'
     */
    @Test
    public void lockDelayTest() {
        // TODO: test lockDelay
    }

    /**
     * Test the property 'TTL'
     */
    @Test
    public void TTLTest() {
        // TODO: test TTL
    }

}
