/*
 * Nomad
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.6
 * Contact: support@hashicorp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Vault
 */
public class VaultTest {
    private final Vault model = new Vault();

    /**
     * Model tests for Vault
     */
    @Test
    public void testVault() {
        // TODO: test Vault
    }

    /**
     * Test the property 'allowTokenExpiration'
     */
    @Test
    public void allowTokenExpirationTest() {
        // TODO: test allowTokenExpiration
    }

    /**
     * Test the property 'changeMode'
     */
    @Test
    public void changeModeTest() {
        // TODO: test changeMode
    }

    /**
     * Test the property 'changeSignal'
     */
    @Test
    public void changeSignalTest() {
        // TODO: test changeSignal
    }

    /**
     * Test the property 'cluster'
     */
    @Test
    public void clusterTest() {
        // TODO: test cluster
    }

    /**
     * Test the property 'disableFile'
     */
    @Test
    public void disableFileTest() {
        // TODO: test disableFile
    }

    /**
     * Test the property 'env'
     */
    @Test
    public void envTest() {
        // TODO: test env
    }

    /**
     * Test the property 'namespace'
     */
    @Test
    public void namespaceTest() {
        // TODO: test namespace
    }

    /**
     * Test the property 'policies'
     */
    @Test
    public void policiesTest() {
        // TODO: test policies
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

}
