/*
 * Nomad
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.6
 * Contact: support@hashicorp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nomadproject.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import io.nomadproject.client.model.ConsulMeshGateway;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ConsulUpstream
 */
public class ConsulUpstreamTest {
    private final ConsulUpstream model = new ConsulUpstream();

    /**
     * Model tests for ConsulUpstream
     */
    @Test
    public void testConsulUpstream() {
        // TODO: test ConsulUpstream
    }

    /**
     * Test the property 'config'
     */
    @Test
    public void configTest() {
        // TODO: test config
    }

    /**
     * Test the property 'datacenter'
     */
    @Test
    public void datacenterTest() {
        // TODO: test datacenter
    }

    /**
     * Test the property 'destinationName'
     */
    @Test
    public void destinationNameTest() {
        // TODO: test destinationName
    }

    /**
     * Test the property 'destinationNamespace'
     */
    @Test
    public void destinationNamespaceTest() {
        // TODO: test destinationNamespace
    }

    /**
     * Test the property 'destinationPeer'
     */
    @Test
    public void destinationPeerTest() {
        // TODO: test destinationPeer
    }

    /**
     * Test the property 'destinationType'
     */
    @Test
    public void destinationTypeTest() {
        // TODO: test destinationType
    }

    /**
     * Test the property 'localBindAddress'
     */
    @Test
    public void localBindAddressTest() {
        // TODO: test localBindAddress
    }

    /**
     * Test the property 'localBindPort'
     */
    @Test
    public void localBindPortTest() {
        // TODO: test localBindPort
    }

    /**
     * Test the property 'localBindSocketMode'
     */
    @Test
    public void localBindSocketModeTest() {
        // TODO: test localBindSocketMode
    }

    /**
     * Test the property 'localBindSocketPath'
     */
    @Test
    public void localBindSocketPathTest() {
        // TODO: test localBindSocketPath
    }

    /**
     * Test the property 'meshGateway'
     */
    @Test
    public void meshGatewayTest() {
        // TODO: test meshGateway
    }

}
