/*
 * Nomad
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.6
 * Contact: support@hashicorp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nomadproject.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DisconnectStrategy
 */
public class DisconnectStrategyTest {
    private final DisconnectStrategy model = new DisconnectStrategy();

    /**
     * Model tests for DisconnectStrategy
     */
    @Test
    public void testDisconnectStrategy() {
        // TODO: test DisconnectStrategy
    }

    /**
     * Test the property 'lostAfter'
     */
    @Test
    public void lostAfterTest() {
        // TODO: test lostAfter
    }

    /**
     * Test the property 'reconcile'
     */
    @Test
    public void reconcileTest() {
        // TODO: test reconcile
    }

    /**
     * Test the property 'replace'
     */
    @Test
    public void replaceTest() {
        // TODO: test replace
    }

    /**
     * Test the property 'stopOnClientAfter'
     */
    @Test
    public void stopOnClientAfterTest() {
        // TODO: test stopOnClientAfter
    }

}
