/*
 * Nomad
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.6
 * Contact: support@hashicorp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nomadproject.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import io.nomadproject.client.model.NamespaceCapabilities;
import io.nomadproject.client.model.NamespaceConsulConfiguration;
import io.nomadproject.client.model.NamespaceNodePoolConfiguration;
import io.nomadproject.client.model.NamespaceVaultConfiguration;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Namespace
 */
public class NamespaceTest {
    private final Namespace model = new Namespace();

    /**
     * Model tests for Namespace
     */
    @Test
    public void testNamespace() {
        // TODO: test Namespace
    }

    /**
     * Test the property 'capabilities'
     */
    @Test
    public void capabilitiesTest() {
        // TODO: test capabilities
    }

    /**
     * Test the property 'consulConfiguration'
     */
    @Test
    public void consulConfigurationTest() {
        // TODO: test consulConfiguration
    }

    /**
     * Test the property 'createIndex'
     */
    @Test
    public void createIndexTest() {
        // TODO: test createIndex
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'meta'
     */
    @Test
    public void metaTest() {
        // TODO: test meta
    }

    /**
     * Test the property 'modifyIndex'
     */
    @Test
    public void modifyIndexTest() {
        // TODO: test modifyIndex
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'nodePoolConfiguration'
     */
    @Test
    public void nodePoolConfigurationTest() {
        // TODO: test nodePoolConfiguration
    }

    /**
     * Test the property 'quota'
     */
    @Test
    public void quotaTest() {
        // TODO: test quota
    }

    /**
     * Test the property 'vaultConfiguration'
     */
    @Test
    public void vaultConfigurationTest() {
        // TODO: test vaultConfiguration
    }

}
