/*
 * Nomad
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.6
 * Contact: support@hashicorp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nomadproject.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import io.nomadproject.client.model.DNSConfig;

/**
 * AllocNetworkStatus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-16T11:56:02.367141Z[Etc/UTC]")
public class AllocNetworkStatus {
  public static final String SERIALIZED_NAME_ADDRESS = "Address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private String address;

  public static final String SERIALIZED_NAME_D_N_S = "DNS";
  @SerializedName(SERIALIZED_NAME_D_N_S)
  private DNSConfig DNS;

  public static final String SERIALIZED_NAME_INTERFACE_NAME = "InterfaceName";
  @SerializedName(SERIALIZED_NAME_INTERFACE_NAME)
  private String interfaceName;


  public AllocNetworkStatus address(String address) {
    
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAddress() {
    return address;
  }


  public void setAddress(String address) {
    this.address = address;
  }


  public AllocNetworkStatus DNS(DNSConfig DNS) {
    
    this.DNS = DNS;
    return this;
  }

   /**
   * Get DNS
   * @return DNS
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DNSConfig getDNS() {
    return DNS;
  }


  public void setDNS(DNSConfig DNS) {
    this.DNS = DNS;
  }


  public AllocNetworkStatus interfaceName(String interfaceName) {
    
    this.interfaceName = interfaceName;
    return this;
  }

   /**
   * Get interfaceName
   * @return interfaceName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getInterfaceName() {
    return interfaceName;
  }


  public void setInterfaceName(String interfaceName) {
    this.interfaceName = interfaceName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AllocNetworkStatus allocNetworkStatus = (AllocNetworkStatus) o;
    return Objects.equals(this.address, allocNetworkStatus.address) &&
        Objects.equals(this.DNS, allocNetworkStatus.DNS) &&
        Objects.equals(this.interfaceName, allocNetworkStatus.interfaceName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, DNS, interfaceName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AllocNetworkStatus {\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    DNS: ").append(toIndentedString(DNS)).append("\n");
    sb.append("    interfaceName: ").append(toIndentedString(interfaceName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

