/*
 * Nomad
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.6
 * Contact: support@hashicorp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nomadproject.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import io.nomadproject.client.model.NamespaceCapabilities;
import io.nomadproject.client.model.NamespaceConsulConfiguration;
import io.nomadproject.client.model.NamespaceNodePoolConfiguration;
import io.nomadproject.client.model.NamespaceVaultConfiguration;

/**
 * Namespace
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-16T11:56:02.367141Z[Etc/UTC]")
public class Namespace {
  public static final String SERIALIZED_NAME_CAPABILITIES = "Capabilities";
  @SerializedName(SERIALIZED_NAME_CAPABILITIES)
  private NamespaceCapabilities capabilities;

  public static final String SERIALIZED_NAME_CONSUL_CONFIGURATION = "ConsulConfiguration";
  @SerializedName(SERIALIZED_NAME_CONSUL_CONFIGURATION)
  private NamespaceConsulConfiguration consulConfiguration;

  public static final String SERIALIZED_NAME_CREATE_INDEX = "CreateIndex";
  @SerializedName(SERIALIZED_NAME_CREATE_INDEX)
  private Integer createIndex;

  public static final String SERIALIZED_NAME_DESCRIPTION = "Description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_META = "Meta";
  @SerializedName(SERIALIZED_NAME_META)
  private Map<String, String> meta = null;

  public static final String SERIALIZED_NAME_MODIFY_INDEX = "ModifyIndex";
  @SerializedName(SERIALIZED_NAME_MODIFY_INDEX)
  private Integer modifyIndex;

  public static final String SERIALIZED_NAME_NAME = "Name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NODE_POOL_CONFIGURATION = "NodePoolConfiguration";
  @SerializedName(SERIALIZED_NAME_NODE_POOL_CONFIGURATION)
  private NamespaceNodePoolConfiguration nodePoolConfiguration;

  public static final String SERIALIZED_NAME_QUOTA = "Quota";
  @SerializedName(SERIALIZED_NAME_QUOTA)
  private String quota;

  public static final String SERIALIZED_NAME_VAULT_CONFIGURATION = "VaultConfiguration";
  @SerializedName(SERIALIZED_NAME_VAULT_CONFIGURATION)
  private NamespaceVaultConfiguration vaultConfiguration;


  public Namespace capabilities(NamespaceCapabilities capabilities) {
    
    this.capabilities = capabilities;
    return this;
  }

   /**
   * Get capabilities
   * @return capabilities
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public NamespaceCapabilities getCapabilities() {
    return capabilities;
  }


  public void setCapabilities(NamespaceCapabilities capabilities) {
    this.capabilities = capabilities;
  }


  public Namespace consulConfiguration(NamespaceConsulConfiguration consulConfiguration) {
    
    this.consulConfiguration = consulConfiguration;
    return this;
  }

   /**
   * Get consulConfiguration
   * @return consulConfiguration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public NamespaceConsulConfiguration getConsulConfiguration() {
    return consulConfiguration;
  }


  public void setConsulConfiguration(NamespaceConsulConfiguration consulConfiguration) {
    this.consulConfiguration = consulConfiguration;
  }


  public Namespace createIndex(Integer createIndex) {
    
    this.createIndex = createIndex;
    return this;
  }

   /**
   * Get createIndex
   * minimum: 0
   * maximum: 384
   * @return createIndex
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getCreateIndex() {
    return createIndex;
  }


  public void setCreateIndex(Integer createIndex) {
    this.createIndex = createIndex;
  }


  public Namespace description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public Namespace meta(Map<String, String> meta) {
    
    this.meta = meta;
    return this;
  }

  public Namespace putMetaItem(String key, String metaItem) {
    if (this.meta == null) {
      this.meta = new HashMap<String, String>();
    }
    this.meta.put(key, metaItem);
    return this;
  }

   /**
   * Get meta
   * @return meta
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, String> getMeta() {
    return meta;
  }


  public void setMeta(Map<String, String> meta) {
    this.meta = meta;
  }


  public Namespace modifyIndex(Integer modifyIndex) {
    
    this.modifyIndex = modifyIndex;
    return this;
  }

   /**
   * Get modifyIndex
   * minimum: 0
   * maximum: 384
   * @return modifyIndex
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getModifyIndex() {
    return modifyIndex;
  }


  public void setModifyIndex(Integer modifyIndex) {
    this.modifyIndex = modifyIndex;
  }


  public Namespace name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Namespace nodePoolConfiguration(NamespaceNodePoolConfiguration nodePoolConfiguration) {
    
    this.nodePoolConfiguration = nodePoolConfiguration;
    return this;
  }

   /**
   * Get nodePoolConfiguration
   * @return nodePoolConfiguration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public NamespaceNodePoolConfiguration getNodePoolConfiguration() {
    return nodePoolConfiguration;
  }


  public void setNodePoolConfiguration(NamespaceNodePoolConfiguration nodePoolConfiguration) {
    this.nodePoolConfiguration = nodePoolConfiguration;
  }


  public Namespace quota(String quota) {
    
    this.quota = quota;
    return this;
  }

   /**
   * Get quota
   * @return quota
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getQuota() {
    return quota;
  }


  public void setQuota(String quota) {
    this.quota = quota;
  }


  public Namespace vaultConfiguration(NamespaceVaultConfiguration vaultConfiguration) {
    
    this.vaultConfiguration = vaultConfiguration;
    return this;
  }

   /**
   * Get vaultConfiguration
   * @return vaultConfiguration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public NamespaceVaultConfiguration getVaultConfiguration() {
    return vaultConfiguration;
  }


  public void setVaultConfiguration(NamespaceVaultConfiguration vaultConfiguration) {
    this.vaultConfiguration = vaultConfiguration;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Namespace namespace = (Namespace) o;
    return Objects.equals(this.capabilities, namespace.capabilities) &&
        Objects.equals(this.consulConfiguration, namespace.consulConfiguration) &&
        Objects.equals(this.createIndex, namespace.createIndex) &&
        Objects.equals(this.description, namespace.description) &&
        Objects.equals(this.meta, namespace.meta) &&
        Objects.equals(this.modifyIndex, namespace.modifyIndex) &&
        Objects.equals(this.name, namespace.name) &&
        Objects.equals(this.nodePoolConfiguration, namespace.nodePoolConfiguration) &&
        Objects.equals(this.quota, namespace.quota) &&
        Objects.equals(this.vaultConfiguration, namespace.vaultConfiguration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(capabilities, consulConfiguration, createIndex, description, meta, modifyIndex, name, nodePoolConfiguration, quota, vaultConfiguration);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Namespace {\n");
    sb.append("    capabilities: ").append(toIndentedString(capabilities)).append("\n");
    sb.append("    consulConfiguration: ").append(toIndentedString(consulConfiguration)).append("\n");
    sb.append("    createIndex: ").append(toIndentedString(createIndex)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    modifyIndex: ").append(toIndentedString(modifyIndex)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nodePoolConfiguration: ").append(toIndentedString(nodePoolConfiguration)).append("\n");
    sb.append("    quota: ").append(toIndentedString(quota)).append("\n");
    sb.append("    vaultConfiguration: ").append(toIndentedString(vaultConfiguration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

