/*
 * Nomad
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.6
 * Contact: support@hashicorp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nomadproject.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * VariableLock
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-16T11:56:02.367141Z[Etc/UTC]")
public class VariableLock {
  public static final String SERIALIZED_NAME_I_D = "ID";
  @SerializedName(SERIALIZED_NAME_I_D)
  private String ID;

  public static final String SERIALIZED_NAME_LOCK_DELAY = "LockDelay";
  @SerializedName(SERIALIZED_NAME_LOCK_DELAY)
  private String lockDelay;

  public static final String SERIALIZED_NAME_T_T_L = "TTL";
  @SerializedName(SERIALIZED_NAME_T_T_L)
  private String TTL;


  public VariableLock ID(String ID) {
    
    this.ID = ID;
    return this;
  }

   /**
   * Get ID
   * @return ID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getID() {
    return ID;
  }


  public void setID(String ID) {
    this.ID = ID;
  }


  public VariableLock lockDelay(String lockDelay) {
    
    this.lockDelay = lockDelay;
    return this;
  }

   /**
   * Get lockDelay
   * @return lockDelay
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLockDelay() {
    return lockDelay;
  }


  public void setLockDelay(String lockDelay) {
    this.lockDelay = lockDelay;
  }


  public VariableLock TTL(String TTL) {
    
    this.TTL = TTL;
    return this;
  }

   /**
   * Get TTL
   * @return TTL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTTL() {
    return TTL;
  }


  public void setTTL(String TTL) {
    this.TTL = TTL;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VariableLock variableLock = (VariableLock) o;
    return Objects.equals(this.ID, variableLock.ID) &&
        Objects.equals(this.lockDelay, variableLock.lockDelay) &&
        Objects.equals(this.TTL, variableLock.TTL);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ID, lockDelay, TTL);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VariableLock {\n");
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("    lockDelay: ").append(toIndentedString(lockDelay)).append("\n");
    sb.append("    TTL: ").append(toIndentedString(TTL)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

