/*
 * Nomad
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.6
 * Contact: support@hashicorp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.nomadproject.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * VolumeMount
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-16T11:56:02.367141Z[Etc/UTC]")
public class VolumeMount {
  public static final String SERIALIZED_NAME_DESTINATION = "Destination";
  @SerializedName(SERIALIZED_NAME_DESTINATION)
  private String destination;

  public static final String SERIALIZED_NAME_PROPAGATION_MODE = "PropagationMode";
  @SerializedName(SERIALIZED_NAME_PROPAGATION_MODE)
  private String propagationMode;

  public static final String SERIALIZED_NAME_READ_ONLY = "ReadOnly";
  @SerializedName(SERIALIZED_NAME_READ_ONLY)
  private Boolean readOnly;

  public static final String SERIALIZED_NAME_SE_LINUX_LABEL = "SELinuxLabel";
  @SerializedName(SERIALIZED_NAME_SE_LINUX_LABEL)
  private String seLinuxLabel;

  public static final String SERIALIZED_NAME_VOLUME = "Volume";
  @SerializedName(SERIALIZED_NAME_VOLUME)
  private String volume;


  public VolumeMount destination(String destination) {
    
    this.destination = destination;
    return this;
  }

   /**
   * Get destination
   * @return destination
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDestination() {
    return destination;
  }


  public void setDestination(String destination) {
    this.destination = destination;
  }


  public VolumeMount propagationMode(String propagationMode) {
    
    this.propagationMode = propagationMode;
    return this;
  }

   /**
   * Get propagationMode
   * @return propagationMode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPropagationMode() {
    return propagationMode;
  }


  public void setPropagationMode(String propagationMode) {
    this.propagationMode = propagationMode;
  }


  public VolumeMount readOnly(Boolean readOnly) {
    
    this.readOnly = readOnly;
    return this;
  }

   /**
   * Get readOnly
   * @return readOnly
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getReadOnly() {
    return readOnly;
  }


  public void setReadOnly(Boolean readOnly) {
    this.readOnly = readOnly;
  }


  public VolumeMount seLinuxLabel(String seLinuxLabel) {
    
    this.seLinuxLabel = seLinuxLabel;
    return this;
  }

   /**
   * Get seLinuxLabel
   * @return seLinuxLabel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSeLinuxLabel() {
    return seLinuxLabel;
  }


  public void setSeLinuxLabel(String seLinuxLabel) {
    this.seLinuxLabel = seLinuxLabel;
  }


  public VolumeMount volume(String volume) {
    
    this.volume = volume;
    return this;
  }

   /**
   * Get volume
   * @return volume
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getVolume() {
    return volume;
  }


  public void setVolume(String volume) {
    this.volume = volume;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VolumeMount volumeMount = (VolumeMount) o;
    return Objects.equals(this.destination, volumeMount.destination) &&
        Objects.equals(this.propagationMode, volumeMount.propagationMode) &&
        Objects.equals(this.readOnly, volumeMount.readOnly) &&
        Objects.equals(this.seLinuxLabel, volumeMount.seLinuxLabel) &&
        Objects.equals(this.volume, volumeMount.volume);
  }

  @Override
  public int hashCode() {
    return Objects.hash(destination, propagationMode, readOnly, seLinuxLabel, volume);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VolumeMount {\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("    propagationMode: ").append(toIndentedString(propagationMode)).append("\n");
    sb.append("    readOnly: ").append(toIndentedString(readOnly)).append("\n");
    sb.append("    seLinuxLabel: ").append(toIndentedString(seLinuxLabel)).append("\n");
    sb.append("    volume: ").append(toIndentedString(volume)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

