/*
 * Nomad
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.6
 * Contact: support@hashicorp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * MultiregionRegion
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-16T11:56:02.367141Z[Etc/UTC]")
public class MultiregionRegion {
  public static final String SERIALIZED_NAME_COUNT = "Count";
  @SerializedName(SERIALIZED_NAME_COUNT)
  private Integer count;

  public static final String SERIALIZED_NAME_DATACENTERS = "Datacenters";
  @SerializedName(SERIALIZED_NAME_DATACENTERS)
  private List<String> datacenters = null;

  public static final String SERIALIZED_NAME_META = "Meta";
  @SerializedName(SERIALIZED_NAME_META)
  private Map<String, String> meta = null;

  public static final String SERIALIZED_NAME_NAME = "Name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NODE_POOL = "NodePool";
  @SerializedName(SERIALIZED_NAME_NODE_POOL)
  private String nodePool;


  public MultiregionRegion count(Integer count) {
    
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getCount() {
    return count;
  }


  public void setCount(Integer count) {
    this.count = count;
  }


  public MultiregionRegion datacenters(List<String> datacenters) {
    
    this.datacenters = datacenters;
    return this;
  }

  public MultiregionRegion addDatacentersItem(String datacentersItem) {
    if (this.datacenters == null) {
      this.datacenters = new ArrayList<String>();
    }
    this.datacenters.add(datacentersItem);
    return this;
  }

   /**
   * Get datacenters
   * @return datacenters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getDatacenters() {
    return datacenters;
  }


  public void setDatacenters(List<String> datacenters) {
    this.datacenters = datacenters;
  }


  public MultiregionRegion meta(Map<String, String> meta) {
    
    this.meta = meta;
    return this;
  }

  public MultiregionRegion putMetaItem(String key, String metaItem) {
    if (this.meta == null) {
      this.meta = new HashMap<String, String>();
    }
    this.meta.put(key, metaItem);
    return this;
  }

   /**
   * Get meta
   * @return meta
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, String> getMeta() {
    return meta;
  }


  public void setMeta(Map<String, String> meta) {
    this.meta = meta;
  }


  public MultiregionRegion name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public MultiregionRegion nodePool(String nodePool) {
    
    this.nodePool = nodePool;
    return this;
  }

   /**
   * Get nodePool
   * @return nodePool
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNodePool() {
    return nodePool;
  }


  public void setNodePool(String nodePool) {
    this.nodePool = nodePool;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultiregionRegion multiregionRegion = (MultiregionRegion) o;
    return Objects.equals(this.count, multiregionRegion.count) &&
        Objects.equals(this.datacenters, multiregionRegion.datacenters) &&
        Objects.equals(this.meta, multiregionRegion.meta) &&
        Objects.equals(this.name, multiregionRegion.name) &&
        Objects.equals(this.nodePool, multiregionRegion.nodePool);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, datacenters, meta, name, nodePool);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultiregionRegion {\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    datacenters: ").append(toIndentedString(datacenters)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nodePool: ").append(toIndentedString(nodePool)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

